name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  # --------------------------------------------------------------------------
  # Linux

  armv7-unknown-linux-gnueabihf:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: armhf
          github_token: ${{ secrets.GITHUB_TOKEN }}
          features: --features=raspberry
          target: armv7-unknown-linux-gnueabihf

  aarch64-unknown-linux-gnu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: arm64
          github_token: ${{ secrets.GITHUB_TOKEN }}
          features: --features=raspberry
          target: aarch64-unknown-linux-gnu

  x86_64-unknown-linux-gnu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: x86_64
          runs_on: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
          github_token: ${{ secrets.GITHUB_TOKEN }}

  x86_64-unknown-linux-musl:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: x86_64
          runs_on: ubuntu-22.04
          target: x86_64-unknown-linux-musl
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # --------------------------------------------------------------------------
  # macOS

  aarch64-apple-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          # This is not true, but simplifies the logic of the action.
          arch: x86_64
          runs_on: macos-12
          target: aarch64-apple-darwin
          github_token: ${{ secrets.GITHUB_TOKEN }}

  x86_64-apple-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: x86_64
          runs_on: macos-12
          target: x86_64-apple-darwin
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # --------------------------------------------------------------------------
  # Windows

  x86_64-pc-windows-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
        with:
          arch: x86_64
          runs_on: windows-2022
          target: x86_64-pc-windows-msvc
          github_token: ${{ secrets.GITHUB_TOKEN }}
